# Generated by Django 5.1.6 on 2025-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_grade_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.IntegerField(),
        ),
    ]
