# Generated by Django 5.1.6 on 2025-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_schedule_day_alter_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.IntegerField(),
        ),
    ]
