# Generated by Django 5.1.6 on 2025-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_grade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
