# Generated by Django 5.1.6 on 2025-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_grade_student_alter_grade_subject_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 20)), name='age_gte_20'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.CheckConstraint(condition=models.Q(('age__lte', 80)), name='age_lte_80'),
        ),
    ]
