# Generated by Django 5.1.6 on 2025-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_teacher_age_gte_20_teacher_age_lte_80'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='score_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', 12)), name='score_lte_12'),
        ),
    ]
