# Generated by Django 5.1.6 on 2025-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
